language: c
sudo: required
dist: trusty

services:
  - docker

env:
  - OS=fedora

install:
  - ./contrib/ci/generate_docker.py

script:
  - docker run --privileged -e CI=true -t -v `pwd`/dist:/build/dist fwupd-$OS

jobs:
  include:
    - stage: abi
      name: "Check for ABI breaks"
      env:
        - OS=fedora
      before_script:
        - ./contrib/ci/generate_docker.py
        - docker build -t fwupd-${OS} -f contrib/ci/Dockerfile-${OS} .
      script:
        - docker run -t -v `pwd`:/build fwupd-${OS} ./contrib/ci/check-abi $(git describe --abbrev=0 --tags) $(git rev-parse HEAD)
